//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public Export()
        {
            this.ExportDetails = new HashSet<ExportDetail>();
        }
    
        public string ExportId { get; set; }
        public System.DateTime ExportDate { get; set; }
        public string ExportUserId { get; set; }
        public string ExportToUserId { get; set; }
        public string ExportReason { get; set; }
        public int SampleNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<ExportDetail> ExportDetails { get; set; }
    }
}
