//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public string Hospital { get; set; }
        public string Lab { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Chief { get; set; }
        public string PosSign { get; set; }
        public string LabID { get; set; }
        public string WebSite { get; set; }
        public string Chief2 { get; set; }
        public string PosSign2 { get; set; }
    }
}
