//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public Import()
        {
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public string ImportId { get; set; }
        public System.DateTime ImportDate { get; set; }
        public string ImportUserId { get; set; }
        public int SampleNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
    }
}
