//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Removal
    {
        public Removal()
        {
            this.RemovalDetails = new HashSet<RemovalDetail>();
        }
    
        public string RemovalId { get; set; }
        public System.DateTime RemovalDate { get; set; }
        public string RemovalUserId { get; set; }
        public string RemovalReason { get; set; }
        public int SampleNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<RemovalDetail> RemovalDetails { get; set; }
    }
}
