//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleSpec
    {
        public SampleSpec()
        {
            this.TubeSamples = new HashSet<TubeSample>();
        }
    
        public string SampleSpecId { get; set; }
        public System.DateTime DateInput { get; set; }
        public string Source { get; set; }
        public Nullable<int> SampleNumber { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string UserInput { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<TubeSample> TubeSamples { get; set; }
    }
}
