//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleHistory
    {
        public long HistoryId { get; set; }
        public string TubeId { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public int Action { get; set; }
        public string UserId { get; set; }
        public double Volume { get; set; }
        public int Status { get; set; }
        public string StorageId { get; set; }
        public int LocationNum { get; set; }
        public string Description { get; set; }
        public int NumberExport { get; set; }
        public Nullable<int> TubeType { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual TubeSample TubeSample { get; set; }
    }
}
