//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SpecLab.Business.Services;

namespace SpecLab.Business.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    
    public partial class SpecLabEntities : DbContext
    {
        public SpecLabEntities()
            : base("name=Entities")
        {
        }
    
    	public SpecLabEntities(ConnectionService service)
            : base(service.getEntityConnection(), false)
        {
    
    	}
    	
    
    	public SpecLabEntities(DbConnection entityConnection, bool contextOwnsConnection)
            : base(entityConnection, contextOwnsConnection)
        {
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Export> Exports { get; set; }
        public DbSet<Import> Imports { get; set; }
        public DbSet<Removal> Removals { get; set; }
        public DbSet<Storage> Storages { get; set; }
        public DbSet<UserHistory> UserHistories { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserRight> UserRights { get; set; }
        public DbSet<SampleSpec> SampleSpecs { get; set; }
        public DbSet<viewExportHistory> viewExportHistories { get; set; }
        public DbSet<TubeSample> TubeSamples { get; set; }
        public DbSet<viewSampleStatistic> viewSampleStatistics { get; set; }
        public DbSet<viewStorageStatistic> viewStorageStatistics { get; set; }
        public DbSet<ExportDetail> ExportDetails { get; set; }
        public DbSet<ImportDetail> ImportDetails { get; set; }
        public DbSet<RemovalDetail> RemovalDetails { get; set; }
        public DbSet<SampleHistory> SampleHistories { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Header> Headers { get; set; }
    }
}
