//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.TubeSamples = new HashSet<TubeSample>();
            this.SampleHistories = new HashSet<SampleHistory>();
        }
    
        public string StorageId { get; set; }
        public int NumberStorage { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> NumRows { get; set; }
        public Nullable<int> NumColumn { get; set; }
    
        public virtual ICollection<TubeSample> TubeSamples { get; set; }
        public virtual ICollection<SampleHistory> SampleHistories { get; set; }
    }
}
