//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewExportHistory
    {
        public string TubeId { get; set; }
        public int SampleType { get; set; }
        public string ExportUserId { get; set; }
        public System.DateTime ExportDate { get; set; }
        public string ExportReason { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string StorageId { get; set; }
        public int NumberStorage { get; set; }
        public int LocationNum { get; set; }
    }
}
