//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLab.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewStorageStatistic
    {
        public string StorageId { get; set; }
        public int LocationNum { get; set; }
        public string TubeId { get; set; }
        public int Status { get; set; }
        public int NumberStorage { get; set; }
        public double Volume { get; set; }
        public int NumberExport { get; set; }
    }
}
